# Schrödinger’s Cat May Be Dead All Along

This Jupyter Notebook is for the paper "Fortela, D.L.; Mikolajczyk, A. Schrödinger’s Cat May Be Dead All Along. Preprints 2023, 2023100009. https://doi.org/10.20944/preprints202310.0009.v1"

In [1]:
# import the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm

In [2]:
# Define the state space
states = ["Dead", "Alive"]
n_states = len(states)
print('Number of hidden states :',n_states)
# Define the observation space
observations = ["Sad", "Happy"]
n_observations = len(observations)
print('Number of observations :',n_observations)


Number of hidden states : 2
Number of observations : 2


In [3]:
# Define the initial state distribution
state_probability = np.array([0.5, 0.5])
print("State probability: ", state_probability)

# Define the state transition probabilities
transition_probability = np.array([[1, 0],
								[0.5, 0.5]])
print("\nTransition probability:\n", transition_probability)
# Define the observation likelihoods
emission_probability= np.array([[0.5, 0.5],
								[0.5, 0.5]])
print("\nEmission probability:\n", emission_probability)


State probability:  [0.5 0.5]

Transition probability:
 [[1.  0. ]
 [0.5 0.5]]

Emission probability:
 [[0.5 0.5]
 [0.5 0.5]]


In [4]:
# Define the sequence of observations
sample_length = 10000
seq = list(range(1))

X = []
for s in seq:
    row = np.random.choice([0, 1], size=sample_length, p=[.5, .5])#.reshape(-1, 1)
    X.append(row)

observations_sequence = np.array(X, dtype=int)

In [7]:
model = hmm.CategoricalHMM(n_components=n_states, init_params='')
model.startprob_ = state_probability
model.transmat_ = transition_probability
model.emissionprob_ = emission_probability
model.fit(observations_sequence, len(X))

logprob, received = model.decode(observations_sequence)

print("Learned emission probs:")
print(model.emissionprob_)

print("Learned transition matrix:")
print(model.transmat_)

Learned emission probs:
[[4.96898883e-01 5.03101117e-01]
 [2.83242376e-06 9.99997168e-01]]
Learned transition matrix:
[[1.         0.        ]
 [0.50155226 0.49844774]]


In [8]:
# Predict the most likely sequence of hidden states
hidden_states = model.predict(observations_sequence)
print("Most likely hidden states:", hidden_states)


Most likely hidden states: [1 0 0 ... 0 0 0]


In [9]:
log_probability, hidden_states = model.decode(observations_sequence,
											lengths = len(observations_sequence),
											algorithm ='viterbi' )

print('Log Probability :',log_probability)
print("Most likely hidden states:", hidden_states)


Log Probability : -6931.27219061577
Most likely hidden states: [1 0 0 ... 0 0 0]


In [10]:
# Also compute the stationary distribution of hidden states

model.get_stationary_distribution()

array([1., 0.])